version: '3.8'

services:
  quickchart:
    image: ianw/quickchart
    container_name: quickchart
    restart: unless-stopped
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quickchart.rule=Host(`quickcharts.tc-automation.fr`)"
      - "traefik.http.routers.quickchart.entrypoints=websecure"
      - "traefik.http.routers.quickchart.tls.certresolver=letsencrypt"
      - "traefik.http.services.quickchart.loadbalancer.server.port=3400"
    networks:
      - web

networks:
  web:
    external: true
