version: '3.8'

services:
  quickchart:
    container_name: quickchart
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: production
    restart: always
